# Generated by Django 5.2.1 on 2025-05-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='budget',
            field=models.CharField(choices=[('Less than 10,000', 'Less than 10,000'), ('Less than 20,000', 'Less than 20,000'), ('Between 20,000 and 50,000', 'Between 20,000 and 50,000'), ('More than 50,000', 'More than 50,000')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
